const $=id=>document.getElementById(id),STORE='qOptionsSubscribersV1';let members=[],selected=new Set(),filter='all',cloudRef=null,saveTimer=null;
let subscribersUndoSnapshot=null;function rememberSubscribersState(){subscribersUndoSnapshot=JSON.stringify(members);document.getElementById('subscribersUndo')?.removeAttribute('disabled')}function undoSubscribersState(){if(!subscribersUndoSnapshot)return toast('لا يوجد إجراء للتراجع');members=JSON.parse(subscribersUndoSnapshot);subscribersUndoSnapshot=null;selected.clear();localWrite();render();if(typeof renderExtendNames==='function')renderExtendNames();document.getElementById('subscribersUndo')?.setAttribute('disabled','');toast('تم التراجع عن آخر إجراء')}
const config={apiKey:'AIzaSyBxX734w0Az7nww2TyfQ2TNwM6Sk0U8pcU',authDomain:'q-options.firebaseapp.com',projectId:'q-options',storageBucket:'q-options.firebasestorage.app',messagingSenderId:'924540887366',appId:'1:924540887366:web:95ce2e8815a95f16e44547',databaseURL:'https://q-options-default-rtdb.europe-west1.firebasedatabase.app'};
function localRead(){try{return JSON.parse(localStorage.getItem(STORE)||'[]')}catch(e){return[]}}function localWrite(){localStorage.setItem(STORE,JSON.stringify(members));clearTimeout(saveTimer);if(cloudRef)saveTimer=setTimeout(()=>cloudRef.set(members),120)}
function iso(d){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}function addMonths(date,n){const d=new Date(date+'T12:00:00'),day=d.getDate();d.setDate(1);d.setMonth(d.getMonth()+n);d.setDate(Math.min(day,new Date(d.getFullYear(),d.getMonth()+1,0).getDate()));return iso(d)}function status(m){const days=Math.ceil((new Date(addMonths(m.start,+m.plan)+'T12:00:00')-new Date(new Date().toDateString()))/86400000);return days<0?{key:'expired',label:'انتهى',days}:days<=7?{key:'soon',label:'قريبًا',days}:{key:'active',label:'مستمر',days}}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function toast(s){$('toast').textContent=s;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,2200)}
function render(){const q=$('search').value.trim().toLowerCase(),counts={active:0,soon:0,expired:0};members.forEach(m=>counts[status(m).key]++);$('total').textContent=members.length;$('active').textContent=counts.active;$('soon').textContent=counts.soon;$('expired').textContent=counts.expired;$('alert').hidden=!counts.expired&&!counts.soon;$('alertText').textContent=`يوجد ${counts.expired} منتهي و${counts.soon} قريب من الانتهاء`;
 document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active-filter',b.dataset.filter===filter));
 const list=members.filter(m=>(filter==='all'||status(m).key===filter)&&(m.name.toLowerCase().includes(q)||m.username.toLowerCase().includes(q))).sort((a,b)=>status(a).days-status(b).days);$('body').innerHTML=list.map(m=>{const s=status(m);return `<tr><td><input class="row-check" type="checkbox" data-id="${m.id}" ${selected.has(m.id)?'checked':''}></td><td><div class="member"><span class="avatar">${esc(m.name[0])}</span><div><strong>${esc(m.name)}</strong><small>${esc(m.username)}</small></div></div></td><td><span class="plan">${+m.plan===1?'شهر واحد':'شهران'}</span></td><td>${m.start}</td><td>${addMonths(m.start,+m.plan)}</td><td class="${s.key}">${s.days<0?'منذ '+Math.abs(s.days)+' يوم':s.days+' يوم'}</td><td><span class="badge ${s.key}">${s.label}</span></td><td><div class="actions"><button data-edit="${m.id}">تعديل</button><button class="delete" data-delete="${m.id}">حذف</button></div></td></tr>`}).join('');$('empty').hidden=!!list.length;$('selectedCount').hidden=!selected.size;$('selectedCount').textContent=`تم تحديد ${selected.size}`;$('selectAll').checked=members.length>0&&selected.size===members.length}
function openForm(m){$('form').reset();$('editId').value=m?.id||'';$('name').value=m?.name||'';$('username').value=m?.username||'';$('start').value=m?.start||iso(new Date());$('plan').value=m?.plan||'1';$('formTitle').textContent=m?'تعديل مشترك':'إضافة مشترك جديد';updateEnd();$('modal').hidden=false}function closeForm(){$('modal').hidden=true}function updateEnd(){$('endPreview').textContent=$('start').value?addMonths($('start').value,+$('plan').value):'—'}
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$('filter').value=filter;render()});$('filter').onchange=e=>{filter=e.target.value;render()};$('search').oninput=render;$('addOpen').onclick=()=>openForm();$('formClose').onclick=$('cancel').onclick=closeForm;$('start').onchange=$('plan').onchange=updateEnd;
$('form').onsubmit=e=>{e.preventDefault();rememberSubscribersState();const id=$('editId').value||String(Date.now()),m={id,name:$('name').value.trim(),username:$('username').value.trim(),start:$('start').value,plan:+$('plan').value};const i=members.findIndex(x=>String(x.id)===String(id));if(i>=0)members[i]=m;else members.unshift(m);localWrite();render();closeForm();toast(i>=0?'تم تعديل المشترك':'تمت إضافة المشترك')};
$('body').onclick=e=>{const check=e.target.closest('.row-check');if(check){check.checked?selected.add(check.dataset.id):selected.delete(check.dataset.id);render();return}const edit=e.target.closest('[data-edit]');if(edit){openForm(members.find(m=>String(m.id)===edit.dataset.edit));return}const del=e.target.closest('[data-delete]');if(del&&confirm('هل تريد حذف هذا المشترك؟')){rememberSubscribersState();members=members.filter(m=>String(m.id)!==del.dataset.delete);selected.delete(del.dataset.delete);localWrite();render();toast('تم حذف المشترك')}};
$('selectAll').onchange=e=>{selected=new Set(e.target.checked?members.map(m=>String(m.id)):[]);render();if(typeof renderExtendNames==='function')renderExtendNames()};$('freeWeek').onclick=()=>{if(!selected.size)return toast('حدد مشتركًا واحدًا على الأقل');members=members.map(m=>selected.has(String(m.id))?{...m,start:iso(new Date(new Date(m.start+'T12:00:00').getTime()+604800000))}:m);localWrite();render();toast(`تمت إضافة أسبوع مجاني إلى ${selected.size} مشترك`)};
async function cloud(){members=localRead();render();try{if(!firebase.apps.length)firebase.initializeApp(config);cloudRef=firebase.database().ref('qOptionsSharedV1/subscribers');const snap=await cloudRef.once('value');if(snap.exists())members=snap.val()||[];else if(members.length)await cloudRef.set(members);cloudRef.on('value',s=>{members=s.val()||[];localStorage.setItem(STORE,JSON.stringify(members));render()});render();toast('تمت مزامنة المشتركين بين الأجهزة')}catch(e){console.error(e);toast('تعذر الاتصال بالمزامنة السحابية')}}cloud();
